app:
  metadata-index: data.bank.local.ops.data-catalog.topic-metadata
  schemas-index: schemas
  search-data:
    fields:
      - topic
      - topicDescription
      - product
      - domain
      - ownerTeam
    weights:
      - 0.20
      - 0.20
      - 0.20
      - 0.20
      - 0.20
