app:
  metadata-index: data.santander.local.ops.data-catalog.topic-metadata
  schemas-index: schemas
  search-data:
    fields:
      - product
      - domain
      - topic
      - topicDescription
    weights:
      - 0.20
      - 0.20
      - 0.20
      - 0.40
