---
context: "data"
company: "bank"
env: "local"
source: "ops"
projects:
  - name: "data-catalog"
    topics:
      - name: "topic-metadata"
        schemas:
          value.schema.file: "/config/schemas/topic_metadata.avsc"
        config:
          replication.factor: "1"
          num.partitions: "1"
    connectors:
      artifacts:
        - path: "/config/connectors/topic-metadata-elastic-sink-connector.json"
          server: "connect"
          name: "topic-metadata-elastic-sink-connector"
        - path: "/config/connectors/schemas-elastic-sink-connector.json"
          server: "connect"
          name: "schemas-elastic-sink-connector"
        - path: "/config/connectors/es-samples-elastic-sink-connector.json"
          server: "connect"
          name: "es-samples-elastic-sink-connector"
        - path: "/config/connectors/uk-samples-elastic-sink-connector.json"
          server: "connect"
          name: "uk-samples-elastic-sink-connector"
        - path: "/config/connectors/global-samples-elastic-sink-connector.json"
          server: "connect"
          name: "global-samples-elastic-sink-connector"
      access_control:
        - principal: ""