---
context: "es"
company: "santander"
env: "local"
source: "ops"
projects:
  - name: "cards"
    topics:
      - name: "card-payments"
        metadataTopic: "data.santander.local.ops.data-catalog.topic-metadata"
        metadata:
          version: "1"
          topic: "es.santander.local.ops.cards.card-payments"
          topicDescription: "ES Card Payment records"
          organization: "Santander"
          domain: "payments"
          product: "card"
          ownerTeam: "ES Card Payments Squad"
          ownerContact: "es_card_payments_squad@mail.com"
        schemas:
          value.schema.file: "/config/schemas/card_payment.avsc"
        config:
          replication.factor: "1"
          num.partitions: "1"