---
context: "es"
company: "bank"
env: "local"
source: "ops"
projects:
  - name: "cards"
    topics:
      - name: "card-payments"
        metadataTopic: "data.bank.local.ops.data-catalog.topic-metadata"
        metadata:
          version: "1"
          topic: "es.bank.local.ops.cards.card-payments"
          topicDescription: "Registro de pago con Tarjeta en España"
          organization: "bank"
          domain: "payments"
          product: "card"
          ownerTeam: "Card Squad España"
          ownerContact: "es_card_squad@mail.com"
        schemas:
          value.schema.file: "/config/schemas/card_payment.avsc"
        config:
          replication.factor: "1"
          num.partitions: "1"
    connectors:
      artifacts:
        - path: "/config/connectors/card-payments-datagen-connector.json"
          server: "connect"
          name: "card-payments-datagen-connector"
      access_control:
        - principal: ""