---
context: "global"
company: "santander"
env: "local"
source: "ops"
projects:
  - name: "products"
    topics:
      - name: "cards"
        metadataTopic: "data.santander.local.ops.data-catalog.topic-metadata"
        metadata:
          version: "1"
          topic: "global.santander.local.ops.products.cards"
          topicDescription: "Información básica relativa a los productos de tipo tarjeta"
          organization: "Santander"
          domain: "products"
          product: "card"
          ownerTeam: "card_squad"
          ownerContact: "card_squad@mail.com"
        schemas:
          value.schema.file: "/config/schemas/card.avsc"
        config:
          replication.factor: "1"
          num.partitions: "1"
      - name: "loans"
        metadataTopic: "data.santander.local.ops.data-catalog.topic-metadata"
        metadata:
          version: "1"
          topic: "global.santander.local.ops.products.loans"
          topicDescription: "Información básica sobre productos de crédito"
          organization: "Santander"
          domain: "products"
          product: "loans"
          ownerTeam: "loans_squad"
          ownerContact: "loans_squad@mail.com"
        schemas:
          value.schema.file: "/config/schemas/loan.avsc"
        config:
          replication.factor: "1"
          num.partitions: "1"
      - name: "clients"
        metadataTopic: "data.santander.local.ops.data-catalog.topic-metadata"
        metadata:
          version: "1"
          topic: "global.santander.local.ops.products.clients"
          topicDescription: "Client Basic Information and Interactions"
          organization: "Santander"
          domain: "clients"
          product: "client"
          ownerTeam: "client_squad"
          ownerContact: "client_squad@mail.com"
        schemas:
          value.schema.file: "/config/schemas/client.avsc"
        config:
          replication.factor: "1"
          num.partitions: "1"
      - name: "product-catalog"
        metadataTopic: "data.santander.local.ops.data-catalog.topic-metadata"
        metadata:
          version: "1"
          topic: "global.santander.local.ops.products.product-catalog"
          topicDescription: "Catálogo de Productos"
          organization: "Santander"
          domain: "products"
          product: "product-catalog"
          ownerTeam: "product_catalog_squad"
          ownerContact: "product_catalog_squad@mail.com"
        schemas:
          value.schema.file: "/config/schemas/product.avsc"
        config:
          replication.factor: "1"
          num.partitions: "1"
    connectors:
      artifacts:
        - path: "/config/connectors/cards-datagen-connector.json"
          server: "connect"
          name: "cards-datagen-connector"
        - path: "/config/connectors/clients-datagen-connector.json"
          server: "connect"
          name: "clients-datagen-connector"
        - path: "/config/connectors/loans-datagen-connector.json"
          server: "connect"
          name: "loans-datagen-connector"
      access_control:
        - principal: ""