---
context: "uk"
company: "bank"
env: "local"
source: "ops"
projects:
  - name: "loans"
    topics:
     - name: "loan-payments"
       metadataTopic: "data.bank.local.ops.data-catalog.topic-metadata"
       metadata:
         version: "1"
         topic: "uk.bank.local.ops.loans.loan-payments"
         topicDescription: "Uk Payment records for loan products"
         organization: "bank"
         domain: "payments"
         product: "loan"
         ownerTeam: "Loans Squad UK"
         ownerContact: "uk_loans_squad@mail.com"
       schemas:
         value.schema.file: "/config/schemas/loan_payment.avsc"
       config:
         replication.factor: "1"
         num.partitions: "1"
    connectors:
      artifacts:
        - path: "/config/connectors/loan-payments-datagen-connector.json"
          server: "connect"
          name: "loan-payments-datagen-connector"
      access_control:
        - principal: ""